-- phpMyAdmin SQL Dump
-- version 4.1.12
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Mar 31, 2017 at 08:15 AM
-- Server version: 5.6.16
-- PHP Version: 5.5.11

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `login`
--

-- --------------------------------------------------------

--
-- Table structure for table `blog`
--

CREATE TABLE IF NOT EXISTS `blog` (
  `id` int(40) NOT NULL AUTO_INCREMENT,
  `title` varchar(100) NOT NULL,
  `featured_image` varchar(9000) NOT NULL,
  `category` varchar(50) NOT NULL,
  `content` longtext NOT NULL,
  `name` varchar(120) NOT NULL DEFAULT 'Shahaji ',
  `createdon` varchar(20) NOT NULL,
  `time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=30 ;

--
-- Dumping data for table `blog`
--

INSERT INTO `blog` (`id`, `title`, `featured_image`, `category`, `content`, `name`, `createdon`, `time`) VALUES
(1, 'test', 'http://www.startup-buzz.com/wp-content/uploads/2016/07/startup-notepad.jpg', 'test', '<p>this is random text</p>\n<p>qwe</p>', 'Shahaji ', 'Fri Mar 24 2017', '2017-03-24 14:39:20'),
(2, 'test', 'http://www.startup-buzz.com/wp-content/uploads/2016/07/startup-notepad.jpg', 'test', '<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less n</p>', 'Shahaji ', 'Fri Mar 24 2017', '2017-03-24 14:39:20'),
(3, 'test', 'http://www.startup-buzz.com/wp-content/uploads/2016/07/startup-notepad.jpg', 'tets', '<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal', 'Shahaji ', 'Fri Mar 24 2017', '2017-03-24 14:39:20'),
(4, 'test', 'http://www.startup-buzz.com/wp-content/uploads/2016/07/startup-notepad.jpg', 'tets', '<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal</p>\n<p>q', 'Shahaji ', 'Fri Mar 24 2017', '2017-03-24 14:39:20'),
(5, 'test', 'http://www.startup-buzz.com/wp-content/uploads/2016/07/startup-notepad.jpg', 'tets', '<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal</p>\n<p>qwert</p>', 'Shahaji ', 'Fri Mar 24 2017', '2017-03-24 14:39:20'),
(6, 'test', 'http://www.startup-buzz.com/wp-content/uploads/2016/07/startup-notepad.jpg', 'tets', '<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal</p>\n<p>qwertyuiop</p>', 'Shahaji ', 'Fri Mar 24 2017', '2017-03-24 14:39:20'),
(7, 'test', 'http://www.startup-buzz.com/wp-content/uploads/2016/07/startup-notepad.jpg', 'tets', '<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal</p>\n<p>qwertyuiopasdfghjkl</p>', 'Shahaji ', 'Fri Mar 24 2017', '2017-03-24 14:39:20'),
(8, 'test', 'http://www.startup-buzz.com/wp-content/uploads/2016/07/startup-notepad.jpg', 'tets', '<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal</p>\n<p>qwertyuiopasdfghjklzxcvb</p>', 'Shahaji ', 'Fri Mar 24 2017', '2017-03-24 14:39:20'),
(9, 'test', 'http://www.startup-buzz.com/wp-content/uploads/2016/07/startup-notepad.jpg', 'tets', '<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal</p>\n<p>qwertyuiopasdfghjklzxcvbrt</p>', 'Shahaji ', 'Fri Mar 24 2017', '2017-03-24 14:39:20'),
(10, 'test', 'http://www.startup-buzz.com/wp-content/uploads/2016/07/startup-notepad.jpg', 'tets', '<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal</p>\n<p>qwertyuiopasdfghjklzxcvbrtiop</p>', 'Shahaji ', 'Fri Mar 24 2017', '2017-03-24 14:39:20'),
(11, 'test', 'http://www.startup-buzz.com/wp-content/uploads/2016/07/startup-notepad.jpg', 'tets', '<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal</p>\n<p>qwertyuiopasdfghjklzxcvbrtiopqw</p>', 'Shahaji ', 'Fri Mar 24 2017', '2017-03-24 14:39:20'),
(12, 'test', 'http://www.startup-buzz.com/wp-content/uploads/2016/07/startup-notepad.jpg', 'tets', '<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal</p>\n<p>qwertyuiopasdfghjklzxcvbrtiopqwsd</p>', 'Shahaji ', 'Fri Mar 24 2017', '2017-03-24 14:39:20'),
(13, 'test', 'http://www.startup-buzz.com/wp-content/uploads/2016/07/startup-notepad.jpg', 'tets', '<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal</p>\n<p>qwertyuiopasdfghjklzxcvbrtiopqwsdzxc</p>', 'Shahaji ', 'Fri Mar 24 2017', '2017-03-24 14:39:20'),
(14, 'test', 'http://www.startup-buzz.com/wp-content/uploads/2016/07/startup-notepad.jpg', 'tets', '<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal</p>\n<p>qwertyuiopasdfghjklzxcvbrtiopqwsdzxcbnm</p>', 'Shahaji ', 'Fri Mar 24 2017', '2017-03-24 14:39:20'),
(15, 'test', 'http://www.startup-buzz.com/wp-content/uploads/2016/07/startup-notepad.jpg', 'tets', '<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal</p>\n<p>qwertyuiopasdfghjklzxcvbrtiopqwsdzxcbnmqazxsw</p>', 'Shahaji ', 'Fri Mar 24 2017', '2017-03-24 14:39:20'),
(16, 'test', 'http://www.startup-buzz.com/wp-content/uploads/2016/07/startup-notepad.jpg', 'tets', '<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal</p>\n<p>qwertyuiopasdfghjklzxcvbrtiopqwsdzxcbnmqazxsw]</p>', 'Shahaji ', 'Fri Mar 24 2017', '2017-03-24 14:39:20'),
(17, 'test', 'http://www.startup-buzz.com/wp-content/uploads/2016/07/startup-notepad.jpg', 'tets', '<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal</p>\n<p>qwertyuiopasdfghjklzxcvbrtiopqwsdzxcbnmqazxsw...</p>', 'Shahaji ', 'Fri Mar 24 2017', '2017-03-24 14:39:20'),
(18, 'test', 'http://www.startup-buzz.com/wp-content/uploads/2016/07/startup-notepad.jpg', 'tets', '<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal</p>\n<p>qwertyuiopasdfghjklzxcvbrtiopqwsdzxcbnmqazxsw...}}{{{{}}}{{{</p>', 'Shahaji ', 'Fri Mar 24 2017', '2017-03-24 14:39:20'),
(19, 'test', 'http://www.startup-buzz.com/wp-content/uploads/2016/07/startup-notepad.jpg', 'tets', '<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal</p>\n<p>qwertyuiopasdfghjklzxcvbrtiopqwsdzxcbnmqazxsw...}}{{{{}}}{{{1234</p>', 'Shahaji ', 'Fri Mar 24 2017', '2017-03-24 14:39:20'),
(20, 'tets', 'http://younginnovator.eu/wp-content/uploads/2014/11/random-questions-for-a-startup-lawyer.jpg', 'vbnnsfod', '<p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.</p>', 'Shahaji ', 'Fri Mar 24 2017', '2017-03-24 14:39:20'),
(21, 'akshay', 'http://i.huffpost.com/gen/1517406/images/o-STARTUP-facebook.jpg', 'akshay', '<p>qwedqw</p>', 'Shahaji ', 'Fri Mar 24 2017', '2017-03-24 14:39:20'),
(22, 'akshay', 'http://i.huffpost.com/gen/1517406/images/o-STARTUP-facebook.jpg', 'akshay', '<p>It is a long established fact that a reader will be distracted by the</p>', 'Shahaji ', 'Fri Mar 24 2017', '2017-03-24 14:39:20'),
(23, 'akshay', 'http://i.huffpost.com/gen/1517406/images/o-STARTUP-facebook.jpg', 'akshay', '<h2>Why do we use it?</h2>\n<p>It is a long established fact that a rea</p>', 'Shahaji ', 'Fri Mar 24 2017', '2017-03-24 14:39:20'),
(24, 'akshay', 'http://i.huffpost.com/gen/1517406/images/o-STARTUP-facebook.jpg', 'akshay', '<p>In ancient manuscripts, another means to divide sentences into paragraphs was a line break (<a title="Newline" href="https://en.wikipedia.org/wiki/Newline">newline</a>) followed by an <a title="Initial" href="https://en.wikipedia.org/wiki/Initial">initial</a> at the beginning of the next paragraph. An initial is an oversize capital letter, sometimes outdented beyond the margin of text. This style can be seen, for example, in the original <a title="Old English" href="https://en.wikipedia.org/wiki/Old_English">Old English</a> manuscript of <a title="Beowulf" href="https://en.wikipedia.org/wiki/Beowulf">Beowulf</a>. Outdenting is still used in English typography, though not commonly.<sup id="cite_ref-Bringhurst2005_4-0" class="reference"><a href="https://en.wikipedia.org/wiki/Paragraph#cite_note-Bringhurst2005-4">[4]</a></sup> Modern English typography usually indicates a new paragraph by <a title="Indentation (typesetting)" href="https://en.wikipedia.org/wiki/Indentation_(typesetting)">indenting</a> the first line. This style can be seen in the (handwritten) <a title="United States Constitution" href="https://en.wikipedia.org/wiki/United_States_Constitution">United States Co</a></p>', 'Shahaji ', 'Fri Mar 24 2017', '2017-03-24 14:39:20'),
(25, 'akshay', 'http://i.huffpost.com/gen/1517406/images/o-STARTUP-facebook.jpg', 'akshay', '<p>In ancient manuscripts, another means to divide sentences into paragraphs was a line break (<a title="Newline" href="https://en.wikipedia.org/wiki/Newline">newline</a>) followed by an <a title="Initial" href="https://en.wikipedia.org/wiki/Initial">initial</a> at the beginning of the next paragraph. An initial is an oversize capital letter, sometimes outdented beyond the margin of text. This style can be seen, for example, in the original <a title="Old English" href="https://en.wikipedia.org/wiki/Old_English">Old English</a> manuscript of <a title="Beowulf" href="https://en.wikipedia.org/wiki/Beowulf">Beowulf</a>. Outdenting is still used in English typography, though not commonly.<sup id="cite_ref-Bringhurst2005_4-0" class="reference"><a href="https://en.wikipedia.org/wiki/Paragraph#cite_note-Bringhurst2005-4">[4]</a></sup> Modern English typography usually indicates a new paragraph by <a title="Indentation (typesetting)" href="https://en.wikipedia.org/wiki/Indentation_(typesetting)">indenting</a> the first line. This style can be seen in the (handwritten) <a title="United States Constitution" href="https://en.wikipedia.org/wiki/United_States_Constitution">United States Co</a></p>\n<h2><span id="Typographical_considerations" class="mw-headline">Typographical considerations</span><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a title="Edit section: Typographical considerations" href="https://en.wikipedia.org/w/index.php?title=Paragraph', 'Shahaji ', 'Fri Mar 24 2017', '2017-03-24 14:39:20'),
(26, 'akshay', 'http://i.huffpost.com/gen/1517406/images/o-STARTUP-facebook.jpg', 'akshay', '<p>In ancient manuscripts, another means to divide sentences into paragraphs was a line break (<a title="Newline" href="https://en.wikipedia.org/wiki/Newline">newline</a>) followed by an <a title="Initial" href="https://en.wikipedia.org/wiki/Initial">initial</a> at the beginning of the next paragraph. An initial is an oversize capital letter, sometimes outdented beyond the margin of text. This style can be seen, for example, in the original <a title="Old English" href="https://en.wikipedia.org/wiki/Old_English">Old English</a> manuscript of <a title="Beowulf" href="https://en.wikipedia.org/wiki/Beowulf">Beowulf</a>. Outdenting is still used in English typography, though not commonly.<sup id="cite_ref-Bringhurst2005_4-0" class="reference"><a href="https://en.wikipedia.org/wiki/Paragraph#cite_note-Bringhurst2005-4">[4]</a></sup> Modern English typography usually indicates a new paragraph by <a title="Indentation (typesetting)" href="https://en.wikipedia.org/wiki/Indentation_(typesetting)">indenting</a> the first line. This style can be seen in the (handwritten) <a title="United States Constitution" href="https://en.wikipedia.org/wiki/United_States_Constitution">United States Co</a></p>\n<h2><span id="Typographical_considerations" class="mw-headline">Typographical considerations</span><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a title="Edit section: Typographical considerations" href="https://en.wikipedia.org/w/index.php?title=Paragraph', 'Shahaji ', 'Fri Mar 24 2017', '2017-03-24 14:39:20'),
(27, 'akshay', 'http://i.huffpost.com/gen/1517406/images/o-STARTUP-facebook.jpg', 'akshay', '"But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure?"', 'Shahaji ', 'Fri Mar 24 2017', '2017-03-24 14:40:45'),
(28, 'yadnsehs', 'http://images.huffingtonpost.com/2016-06-05-1465144380-7190217-startups.jpg', 'yadnesh', '"But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure?"', 'Shahaji ', 'Fri Mar 24 2017', '2017-03-24 14:43:04'),
(29, 'session', 'https://cdn.theculturetrip.com/wp-content/uploads/2016/12/9128545945_c60ce57e15_k.jpg', 'session', '<p><strong><a title="Jean Bellette" href="https://en.wikipedia.org/wiki/Jean_Bellette">Jean Bellette</a></strong> (25 March 1908', 'Yadnesh Kulkarni', 'Sat Mar 25 2017', '2017-03-25 13:56:42');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
